version: '3.2'
networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/24

services:
  dns:
    image: coredns/coredns:1.2.0
    command: -conf /etc/coredns/Corefile
    container_name: dns
    networks:
      default:
        ipv4_address: 172.19.0.2
        aliases: [ns1.localhost]
    ports:
      - "5300:53/udp"
    volumes:
      - ./docker/dns:/etc/coredns

  postgres:
    image: postgres:9.6
    depends_on: [dns]
    dns: [172.19.0.2]
    networks:
      default:
        aliases: [db1.localhost]
    ports:
      - "5432:5432"
    # environment:
      # - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      # - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d

  kafka:
    image: landoop/fast-data-dev:1.1.0
    depends_on: [dns]
    dns: [172.19.0.2]
    environment:
      - ADV_HOST=kafka.localhost
      - SAMPLEDATA=0
    networks:
      default:
        aliases: [kafka.localhost]
    ports:
      - "2181:2181"
      - "9092:9092"
      - "3030:3030"
      - "8081:8081"

  scdf:
    image: springcloud/spring-cloud-dataflow-server-local:1.7.0.RELEASE
    container_name: scdf
    depends_on: [dns, postgres, config-server]
    dns: [172.19.0.2]
    networks:
      default:
        aliases: [dataflow.localhost]
    ports:
      - "9393:9393"
    volumes:
      - ~/.m2:/root/.m2
    environment:
      - spring.cloud.deployer.local.javaOpts=-Dspring.profiles.active=docker
      - spring.cloud.dataflow.applicationProperties.stream.spring.profiles.include=docker

      - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.brokers=kafka.localhost:9092
      - spring.cloud.dataflow.applicationProperties.stream.spring.cloud.stream.kafka.binder.zkNodes=kafka.localhost:2181

      - spring.datasource.url=jdbc:postgresql://db1.localhost:5432/scdf
      - spring.datasource.username=scdf
      - spring.datasource.password=scdf
      - spring.datasource.driver-class-name=org.postgresql.Driver

  scdf-config:
    image: alpine
    depends_on: [dns, scdf]
    volumes:
      - ./docker:/docker
    command: docker/scdf/setup.sh

  config-server:
    image: hyness/spring-cloud-config-server
    container_name: config-server
    depends_on: [dns]
    dns: [172.19.0.2]
    networks:
      default:
        aliases: [config-server.localhost]
    ports:
      - "8888:8888"
    volumes:
      - ~/workspace/clp-cloud-config:/root/clp-cloud-config
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=file://root/clp-cloud-config/
      - SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCHPATHS=**/*

  mongo:
    image: mongo
    restart: always
    depends_on: [dns, scdf]
    dns: [172.19.0.2]
    networks:
      default:
        aliases: [mongo.localhost]
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-config:
    image: mongo
    depends_on: [dns, mongo]
    dns: [172.19.0.2]
    networks:
      default:
        aliases: [mongo-config.localhost]
    volumes:
    - ./docker:/docker
    command: docker/mongo/setup.sh

  mongo-express:
    image: mongo-express
    restart: always
    depends_on: [dns, scdf]
    dns: [172.19.0.2]
    networks:
      default:
        aliases: [mongo-express.localhost]
    ports:
      - "8889:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example